### ISSUE TITLE
dangling volumes due to `VOLUME /var/log/letsencrypt`

### ISSUE THREAD

**Issue by abdeldjalil-fellah** [openspeedtest/Docker-Image#24]
because of `VOLUME /var/log/letsencrypt` in `Dockerfile` dangling volumes keep created when no volume is set for /var/log/letsencrypt in docker compose file. please remove that statement to avoid this issue.

**Comment by mike2307** [comment]
Does anyone know of a possibility to do something like a dummy mapping to avoid this issue?

**Comment by quinnell** [comment]
Am experiencing the same issue. No resolution?

**Comment by piniou** [comment]
Simply mount volume on `/var/log/letsencrypt`


cli : 

`docker run --rm -d --name speedtest -v openspeedtest:/var/log/letsencrypt -p 3000 openspeedtest/latest`

docker-compose.yml : 

```
volumes:
  openspeedtest:
services:
    image: openspeedtest/latest
    hostname: speedtest
    expose:
      - 3000
    volumes:
      - openspeedtest:/var/log/letsencrypt
```


Adjust the port configuration depending on whether you're behind a reverse proxy or not.
