### ISSUE TITLE
Versioned Docker images

### ISSUE THREAD

**Issue by ShonP40** [openspeedtest/Docker-Image#4]
Could you guys upload versioned Docker images & GitHub releases in addition to the `latest` image? (e.g. `openspeedtest:1.0.0`)

This would allow me to add OpenSpeedTest to Umbrel with the ability to update it without needing to reinstall it.

See https://github.com/ShonP40/umbrel-apps/tree/master/shonp40-home-assistant as an example

**Comment by openspeedtest** [comment]
openspeedtest/latest:latest  to openspeedtest/latest:v2.5.4

**Comment by ShonP40** [comment]
Should probably be `<organization>/<app>:<version>`

**Comment by openspeedtest** [comment]
Creating new images will confuse people.
No breaking changes will be introduced to this image.
latest is the app name, which is not ideal, but that is what I chose when I created this. 
I was planning to add something like this `openspeedtest/latest:v2.5.4` 

Did you try this?

`pull_policy: always`

````
version: '3.3'
services:
    speedtest:
        restart: unless-stopped
        container_name: openspeedtest
        ports:
            - '3000:3000'
            - '3001:3001'
        image: openspeedtest/latest
        pull_policy: always
````
https://stackoverflow.com/a/66136860/16065516

If that is not working, we can add a new tag with the version name. 
`openspeedtest/latest:v2.5.4`
