### ISSUE TITLE
Support for reverse proxy path based routing

### ISSUE THREAD

**Issue by ThorpeJosh** [openspeedtest/Docker-Image#9]
Hi, Thanks for the awesome tool!

I tried putting this behind a reverse proxy so that I can access it at the path `https://my.domain/speedtest`.
I added a traefik stripprefix middleware that strips the `/speedtest` from the path and the page loads correctly; however as soon as I click start I get a 'Network Error' as it seems that my browser is attempting to reach `https://my.domain/upload?.....` but for it to route through my reverse proxy correctly it needs to be `https://my.domain/speedtest/upload?....` instead.

I have a lot of services and I want to setup this speedtest service on many servers so want to avoid creating a new domain for each instance. I do path based routing for many other applications, most work, some don't. The two ways applications seem to support path based routing is to use relative paths and not absolute, or by having an environment variable that allows me to set the application base path, eg. `BASE=/speedtest` with the default as `BASE=/`.

Would this be something you could support?

Thanks,
Josh

**Comment by openspeedtest** [comment]
I recently took a test at https://somedot.com/test/. The download and upload processes worked correctly. The app requested the URL https://somedot.com/test/downloading for downloading and https://somedot.com/test/upload for uploading. If you can either post the URL or send it to [support@openspeedtest.com](mailto:support@openspeedtest.com), that would be helpful.

**Comment by openspeedtest** [comment]
Or you can edit index.html https://github.com/openspeedtest/Speed-Test/blob/main/index.html#L51

````
  var openSpeedTestServerList = [
        {"ServerName":"Home", "Download":"https://somedot.com/test/downloading", "Upload":"https://somedot.com/test/upload", "ServerIcon":"DefaultIcon"}
      ];
````

Irrespective of the domain name, it will request for the exact same address for both download and upload operations.

**Comment by ThorpeJosh** [comment]
> I recently took a test at https://somedot.com/test/.

I don't understand. I tried this and got an nginx 404 since the path `/test` doesn't exist. It would only work on the `/` root path

**Comment by ThorpeJosh** [comment]
How'd did you get that to work?
Are you using the official docker image?

In the context of using the docker image, the second option is very hacky. Can that be made an environment variable so that I don't have to build a custom image?

**Comment by openspeedtest** [comment]
That was not a docker image.
Now I tested docker image and it's working fine. 
````
        - "traefik.enable=true"
        - "traefik.http.routers.openspeedtest.rule=Host(`home.vishnu.pro`) && PathPrefix(`/test/`)"
        - "traefik.http.routers.openspeedtest.middlewares=strip-prefix"
        - "traefik.http.services.openspeedtest.loadbalancer.server.port=3000"
        - "traefik.http.middlewares.strip-prefix.stripprefix.prefixes=/test/"
````

**Comment by openspeedtest** [comment]
Like I mentioned here https://github.com/openspeedtest/Speed-Test/issues/4#issuecomment-1229157193 you may need to add limit. If the performance tradeoff is acceptable, you can continue using configuration with limit. Otherwise, consider moving the "openspeedtest" service to a separate subdomain for better performance and isolation.
````
        - "traefik.enable=true"
        - "traefik.http.routers.openspeedtest.rule=Host(`lol.vishnu.pro`) && PathPrefix(`/test/`)"
        - "traefik.http.routers.openspeedtest.middlewares=strip-prefix,limit"
        - "traefik.http.services.openspeedtest.loadbalancer.server.port=3000"
        - "traefik.http.middlewares.strip-prefix.stripprefix.prefixes=/test/"
        - "traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=35000000"
        - "traefik.http.middlewares.limit.buffering.memRequestBodyBytes=35000000"
        - "traefik.http.middlewares.limit.buffering.maxResponseBodyBytes=35000000"
        - "traefik.http.middlewares.limit.buffering.memResponseBodyBytes=35000000"
 ````

**Comment by ThorpeJosh** [comment]
That is exactly the traefik config I was using. After pulling the latest image (released a few days ago), it started to work correctly.

Thanks

**Comment by robertofalk** [comment]
@ThorpeJosh did you manage to solve the problem? I'm also deploying on k3s and using a traefik middleware but it's not working:
``` yml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix
  namespace: speedtest
spec:
  stripPrefix:
    prefixes:
      - /speedtest
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: speedtest-ingress
  namespace: speedtest
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: speedtest-strip-prefix@kubernetescrd
spec:
  rules:
  - http:
      paths:
      - path: /speedtest
        pathType: Prefix
        backend:
          service:
            name: speedtest-service
            port:
              name: http
```
The page partially opens but the html tries to load without using the /speedtest, so it doesn't find anything.
Thanks!
